//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR12
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterServiceType
    {
        public int ID { get; set; }
        public int MasterID { get; set; }
        public int ServiceTypeID { get; set; }
    
        public virtual ServiceType ServiceType { get; set; }
        public virtual User User { get; set; }
    }
}
