//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR12
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int ID { get; set; }
        public int ClientID { get; set; }
        public int TimetableID { get; set; }
        public int ServiceID { get; set; }
        public int RecordStatusID { get; set; }
        public string Comment { get; set; }
        public int PaymentTypeID { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual RecordStatus RecordStatus { get; set; }
        public virtual Service Service { get; set; }
        public virtual Timetable Timetable { get; set; }
        public virtual User User { get; set; }
    }
}
