//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR12
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionPlace
    {
        public int ID { get; set; }
        public int SessionID { get; set; }
        public int PlaceID { get; set; }
        public bool Status { get; set; }
    
        public virtual Places Places { get; set; }
        public virtual Sessions Sessions { get; set; }
    }
}
